# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: Docker Scout
description: List vulnerabilities in images; find better base images and upload an image SBOM to Docker Scout
author: Docker

inputs:
  command:
    required: true
    description: Command to run
  debug:
    required: false
    description: Debug
  summary:
    required: false
    description: Publish the output as GitHub Action summary
    default: true

  image:
    required: false
    description: Image to analyze
  platform:
    required: false
    description: Platform of the image to analyze
  type:
    required: false
    description: Type of image
  ref:
    required: false
    description: Ref if needed

  # compare flags
  to:
    required: false
    description: Image to compare to
  to-type:
    required: false
    description: Type of image to compare
  to-ref:
    required: false
    description: Ref of image to compare
  to-stream:
    required: false
    description: Compare to image in stream
  to-latest:
    required: false
    description: Compare to latest pushed image
  to-app:
    required: false
    description: Name of the application when recording to a stream

  # filter flags
  ignore-base:
    required: false
    description: Ignore vulnerabilities from base image
  ignore-unchanged:
    required: false
    description: Filter out unchanged packages
  ignore-vex:
    required: false
    description: Filter out CVEs that are marked not affected by a VEX statement
  only-fixed:
    required: false
    description: Filter to fixable CVEs
  only-unfixed:
    required: false
    description: Filter to unfixed CVEs
  only-severities:
    required: false
    description: Comma separated list of severities (critical, high, medium, low, unspecified) to filter CVEs by
  only-package-types:
    required: false
    description: Comma separated list of package types (like apk, deb, rpm, npm, pypi, golang, etc)
  exit-code:
    required: false
    description: Return exit code '2' if vulnerability changes are detected

  dockerhub-user:
    required: false
    description: Docker Hub User
  dockerhub-password:
    required: false
    description: Docker Hub PAT

  # credentials needed to pull private images
  registry-user: 
    description: Registry user to pull images
    required: false
  registry-password: 
    description: Registry password to pull images
    required: false

  # comments
  github-token:
    description: GitHub Token to write comments
    default: ${{ github.token }}
    required: false
  write-comment:
    description: Write the output as a Pull Request comment
    required: false
    default: true
  keep-previous-comments:
    description: If set, keep but hide previous comment. If not set, keep and update one single comment per job
    required: false

runs:
  using: node16
  main: index.js

branding:
  icon: shield
  color: gray-dark
